### ISSUE TITLE
Update reference config file

### ISSUE THREAD

**Issue by gmilescu** [near/nearcore-support#2]
Context: As per messages form the NEAR Validators Telegram channel, the config.json that is available through the [near-nodes.io instructions](https://near-nodes.io/rpc/run-rpc-node-without-nearup#mainnet) is outdated.

At least these two fields need to be adjusted:
- store.state_snapshot_config.compaction_enabled
- store.state_snapshot_compaction_enabled

Contact point: Telegram, https://t.me/near_validators/12672

Log files: N/A

Config file: N/A

**Comment by gmilescu** [comment]
@marcelo-gonzalez We also need to update the shard cache size [recommendations](https://t.me/c/1331540142/20111):

    "per_shard_max_bytes": {
         "s1.v1": 50000000,
         "s3.v1": 3000000000,
         "s1.v2": 50000000,
         "s2.v2": 3000000000,
         "s4.v2": 3000000000,
         "s1.v3": 50000000,
         "s2.v3": 1500000000,
         "s3.v3": 1500000000,
         "s5.v3": 3000000000
       },

**Comment by marcelo-gonzalez** [comment]
the new one has been uploaded. also took the liberty to change `load_mem_tries_for_all_shards` -> `load_mem_tries_for_tracked_shards`
