### ISSUE TITLE
[Node Issue]: can't keep my node in sync

### ISSUE THREAD

**Issue by baldator** [near/nearcore-support#5]
### What happened?

My node since few weeks can't keep in sync: I've upgraded the server and I have much more than the required hw specs. I can't see where the problem is and I'd need your help to find it out. I've a bare metal server with 8 physical cores and 64GB of ram.
The near data folder run on a dedicated volume group supported by 2 NVMe drives (6TB total size).

I'm about to give up running my node: I'm investing in hw much more than I'm getting in rewards...

### Version

```shell
1.39.0
```

### Node type

RPC (Default)

### Are you a validator?

- [X] I am a validator.

### Relevant log output

```shell
I regularly have the following logs:

Apr 18 22:49:57 p-near-03 neard[836]: 2024-04-18T20:49:57.247637Z  INFO stats: #117128349 Downloading blocks 0.00% (2 left; at 117128345) 150 peers ⬇ 21.8 MB/s ⬆ 24.2 MB/s 0.80 bps 946 Tgas/s CPU: 532%, Mem: 13.2 GB
Apr 18 22:50:07 p-near-03 neard[836]: 2024-04-18T20:50:07.250876Z  INFO stats: #117128356 Downloading blocks 88.89% (1 left; at 117128353) 150 peers ⬇ 21.7 MB/s ⬆ 24.9 MB/s 0.70 bps 852 Tgas/s CPU: 398%, Mem: 12.9 GB
```

### Node head info

```shell
RUST_LOG=warn /home/near/.near/neard --home /home/near/.near/ --unsafe-fast-startup view-state scan-db-column --column BlockMisc
2024-04-18T21:04:56.742399Z  WARN genesis: Skipped genesis validation
2024-04-18T21:04:56.742417Z  WARN genesis: Skipped genesis validation
thread 'main' panicked at tools/state-viewer/src/cli.rs:118:55:
called `Result::unwrap()` on an `Err` value: IO(Custom { kind: Other, error: Error { message: "Corruption: Can't access /59018251.sst: IO error: No such file or directory: while stat a file for size: /home/near/.near/data/59018251.sst: No such file or directory\nCan't access /59018188.sst: IO error: No such file or directory: while stat a file for size: /home/near/.near/data/59018188.sst: No such file or directory\n" } })
stack backtrace:
   0: rust_begin_unwind
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/result.rs:1653:5
   3: state_viewer::cli::StateViewerSubCommand::run
   4: neard::cli::NeardCmd::parse_and_run
   5: neard::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Aborted (core dumped)


I checked and the file is looking for isn't there
```

### Node upgrade history

```shell
I upgraded from 1.38.2 on April 9th arount 1AM GMT
```

### DB reset history

```shell
I restarted from snapshot on April 2nd
```

**Comment by wacban** [comment]
> Can't access /59018251.sst 

You may need to stop your node while running the view-state

> 1.38.2 

Can you upgrade to 1.39.1 and report back? This latest release contains performance improvements that may help you.

**Comment by baldator** [comment]
I've upgraded my node. I'll keep you posted.

**Comment by baldator** [comment]
so far so good: I missed 2 chuncks over the last 2 epochs. I suggest we keep the ticket open for the next 2-3 epochs to confirm everything is ok, but 1.39.1 seems much much better than previous versions.

Thank you for the support!

**Comment by wacban** [comment]
> I'm about to give up running my node: I'm investing in hw much more than I'm getting in rewards... 

I'm sorry to hear that. We are currently working on stateless validation project that will allow smaller validators to track only a subset of shards. This will reduce the hardware requirements and operational costs. If you don't mind sharing, what is the main driver of cost for you (mem/ cpu/ disk/ other)? 

Also cc @gmilescu Epoch Sync would likely help here too.

**Comment by baldator** [comment]
I confirm it's working much better. I think we can close the issue.

The main driver for cost is mainly the disk, followed by cpu and memory. The problem for me wasn't really the cost, it was more that it's complicated to find what is the limiting resource, considering I wasn't able to find a local bottleneck on the server and its specs are higher than the recommended ones.

Maybe it would be interesting to have an advanced troubleshooting guide: if you have any hint/existing guide/suggestions I can sort everything and work on a troubleshooting guide.

**Comment by wacban** [comment]
> The main driver for cost is mainly the disk, followed by cpu and memory.  

Thanks for sharing! I'll share that with the team and perhaps we'll be able to improve things. 

For troubleshooting here is the "turn if off and on again" hints:
* Make sure you're running the latest release https://github.com/near/nearcore/releases 
* Make sure you're running the latest config [mainnet config](https://s3.us-west-1.amazonaws.com/build.nearprotocol.com/nearcore-deploy/mainnet/config.json)
* If your database is corrupted download the latest snapsthot as described [here](https://near-nodes.io/intro/node-data-snapshots)
* If your node is behind by many epochs either download the latest snapshot as above or enable state sync [docs](https://github.com/near/nearcore/blob/master/docs/misc/state_sync_from_external_storage.md#google-cloud-storage)
